---
blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://github.com/khulnasoft-lab/k8s-node-collector/discussions
    about: If you have a question about k8s node collector.
